name: Web Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build web app
        run: yarn build

      - name: Create web archive
        run: |
          cd dist
          zip -r ../zeroboard-web-${{ github.ref_name }}.zip .
          cd ..

      - name: Create Web Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            zeroboard-web-${{ github.ref_name }}.zip