name: Test Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-web-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build web app
        run: npm run build

      - name: Test build output
        run: |
          if [ ! -f "dist/index.html" ]; then
            echo "Build failed: index.html not found"
            exit 1
          fi
          echo "Build successful"

  test-electron-build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Test Electron build (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          npm run electron-build-mac
          ls -la dist-electron/
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Test Electron build (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          npm run electron-build-win
          dir dist-electron/